dist: xenial
sudo: required
language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

cache:
    directories:
      - ~/.bazel_binaries
      - .bazel_cache

# some could be global, but these are OS-specific and ought not to be included
# in the UI or the cache key
_linux: &linux
  os: linux
_osx: &osx
  os: osx
  osx_image: xcode10.1

jobs:
  include:
# Lint
    - stage: lint
      <<: *osx
      env: BAZEL_VERSION=1.0.0
      script: ./scripts/travis.sh lint
    - <<: *linux
      env: BAZEL_VERSION=1.1.0
      script: ./scripts/travis.sh lint
# Test - This also takes care of verifying things build
    - stage: test
      <<: *osx
      env: BAZEL_VERSION=1.0.0
      script: ./scripts/travis.sh test
    - <<: *linux
      env: BAZEL_VERSION=1.0.0
      script: ./scripts/travis.sh test
    - <<: *osx
      env: BAZEL_VERSION=1.1.0
      script: ./scripts/travis.sh test
    - <<: *linux
      env: BAZEL_VERSION=1.1.0
      script: ./scripts/travis.sh test
