load("@rules_scala_annex//rules:register_toolchain.bzl", "register_zinc_toolchain")
load("//:versions.bzl", "scala_3_version")

compiler_classpath_3 = [
    "@hocon_maven//:org_scala_lang_scala3_compiler_3",
    "@hocon_maven//:org_scala_lang_scala3_library_3",
]

runtime_classpath_3 = [
    "@hocon_maven//:org_scala_lang_scala3_library_3",
    "@hocon_maven//:org_scala_lang_scala3_interfaces",
    "@hocon_maven//:org_scala_lang_tasty_core_3",
]

register_zinc_toolchain(
    name = "zinc_3",
    compiler_bridge = "@hocon_maven//:org_scala_lang_scala3_sbt_bridge",
    compiler_classpath = compiler_classpath_3,
    runtime_classpath = runtime_classpath_3,
    version = scala_3_version,
    visibility = ["//visibility:public"],
)
