name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-version: 1.20.0

      - run: ./scripts/format.sh check
      - run: ./tests/run_tests.sh
      - run: bazel shutdown
