name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/format.sh check
      - run: ./tests/run_tests.sh
