name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel_version }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        bazel_version: [bazelbuild/5.3.0, bazelbuild/6.3.2]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g @bazel/bazelisk
      - run: ./scripts/format.sh check
      - run: ./tests/run_tests.sh
